# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import face_pb2 as face__pb2


class FaceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFrame = channel.unary_unary(
                '/FaceService/GetFrame',
                request_serializer=face__pb2.FrameRequest.SerializeToString,
                response_deserializer=face__pb2.Frame.FromString,
                )
        self.DisplayLocations = channel.unary_unary(
                '/FaceService/DisplayLocations',
                request_serializer=face__pb2.Locations.SerializeToString,
                response_deserializer=face__pb2.LocationResponse.FromString,
                )


class FaceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplayLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFrame,
                    request_deserializer=face__pb2.FrameRequest.FromString,
                    response_serializer=face__pb2.Frame.SerializeToString,
            ),
            'DisplayLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplayLocations,
                    request_deserializer=face__pb2.Locations.FromString,
                    response_serializer=face__pb2.LocationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FaceService/GetFrame',
            face__pb2.FrameRequest.SerializeToString,
            face__pb2.Frame.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisplayLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FaceService/DisplayLocations',
            face__pb2.Locations.SerializeToString,
            face__pb2.LocationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
